name: Test and Build

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow on tags that match the pattern 'vX.Y.Z'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build package
        run: python setup.py sdist bdist_wheel
        # This will create a source distribution and a wheel distribution in the dist/ folder

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
